name: ZombiesNacukatEdition
version: '${project.version}'
main: org.nacukat.zombiesnacukatedition.ZombiesNacukatEdition
api-version: 1.19
commands:
  rew:
  open-shop:
  setmap:
  reload-config:
  toggle-particles:
  gold:
  start:
  startCounting: